#!/usr/bin/env python

from configparser import ConfigParser
import signal
import sys

from notifier.socket import Socket
from notifier.server_query import ServerQuery
from notifier.version_manager import VersionManager
from notifier.logger import log_error, log_info


def sigterm_handler(_signo, _stack_frame):
    # Raises SystemExit(0):
    sys.exit(0)

signal.signal(signal.SIGTERM, sigterm_handler)


if __name__ == "__main__":
    conf = ConfigParser()
    conf.read("config.ini")
    log_info("loaded config")

    try:
        custom_socket = Socket()
        custom_socket.connect(
            conf.get("ts3", "host"),
            conf.getint("ts3", "port")
        )
    except:
        custom_socket.close()

    if not custom_socket.is_connected:
        log_error("socket not conntected")
        sys.exit(1)

    try:
        server_query = ServerQuery(custom_socket)
        server_query.connect(
            conf.get("ts3", "username"),
            conf.get("ts3", "password"),
            conf.get("ts3", "server_id")
        )

        version_manager = VersionManager(
            conf.get("notifier", "current_version")
        )

        server_query.notifier(
            conf.get("notifier", "server_group_id"),
            version_manager
        )
    finally:
        server_query.close()
